
# example


# A name used to identify the model. Must be unique.
name = "example"

# Default profile for the model. Pick one table from "profiles.toml".
# The flags from your chosen profile will overwrite the default ones.
profile = "default"


# Relative path of your files.
[files]
--model = "model.gguf"
--mmproj = "mmproj.gguf"
--model-draft = "drafter-mtp.gguf"
--chat-template-file = "chat-template.jinja"


# Additional llama.cpp parameters.
[parameters]
--spec-type = "ngram-mod,draft-mtp"
--fit = "on"
--jinja = ""
