# Configurations file. 


# The absolute path where your models are stored. The search is recursive, so pick the root folder. 
# Watch out for correct separator. Use the standard "/".
root =  "C:/AI"


# The command to open Your file editor.
# I recommend VS Code (don't forget the sufix ".cmd" if you're using windows).
editor = "code.cmd"


# The path to your browser's executable file.
# (OPTIONAL: Delete if you don't want to automatically open the browser)
browser_path = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
