# Profiles TOML. Create here your profiles with any llama.cpp flags. 


# The flags used by default in every model! Keep here what is mostly unchanged.
# If you need to set something specific, use the model's own TOML, or create a profile bellow.
[default]
--fit = "on"              # For default flags, only set the key and the value.
--agent = ""              # For flags without value, just use an empty string.
--jinja = ""              
--kv-unified = ""
--flash-attn = "on"

--no-mmproj-offload = ""
--spec-type = "ngram-mod"
--cache-type-k = "q8_0"
--cache-type-v = "q8_0"

--threads = 8
--parallel = 1
--verbosity = 3

--port = 9931
--host = "127.0.0.1"
--ctx-checkpoints = 2
--sleep-idle-seconds = 900


#  An example of working profile, with sampling and flags set.
[off]
--temp = 1.00
--top-p = 0.95
--top-k = 20
--min-p = 0.05
--repeat-penalty = 1.0
--presence-penalty = 0.0

--reasoning = "off"


#  Gemma's Uncensored sampling
[hauhau]
--temp = 0.60
--top-k = 64
--top-p = 0.90
--min-p = 0.05
--repeat-penalty = 1.1



# Qwen3.8 27B's extra high reasoning
[xhigh]
--temp = 1.00
--top-p = 0.95
--top-k = 20
--min-p = 0.0
--repeat-penalty = 1.0
--presence-penalty = 0.0

--reasoning = "on"
--reasoning-preserve = ""
--reasoning-effort = "xhigh"