# Profile's toml. Create here your profiles with any llama.cpp flags you want. 
# Just keep in mind that those will be replaced by the model's parameters if possible.


# The default flags used in EVERY model!  Keep here what is mostly unchanged.
# If you need to set something specific, use the model's toml, or even the profiles bellow.
[default]
--fit = "on"

--jinja = ""
--kv-unified = ""
--flash-attn = "on"

--port = 9931
--host = "127.0.0.1"
--sleep-idle-seconds = 900

--threads = 8
--parallel = 1
--verbosity = 3

--tools = "all"
--ui-mcp-proxy = ""
--cors-origins = "localhost"
--ctx-checkpoints = 2


#  An example of profile, with sampling and flags set.
[off]
--temp = 1.00
--top-p = 0.95
--top-k = 64
--min-p = 0.05
--presence-penalty = 0.0
--repeat-penalty = 1.1

--reasoning = "off"
--reasoning-effort = "low"


#  Gemma's Uncensored sampling
[hauhau]
--temp = 0.60
--top-k = 64
--top-p = 0.90
--min-p = 0.05
--repeat-penalty = 1.1


# A Qwen3.8 27B's extra high reasoning
[xhigh]
--temp = 1.00
--top-p = 0.95
--top-k = 20
--min-p = 0.0
--presence-penalty = 0.0
--repeat-penalty = 1.0

--reasoning = "on"
--reasoning-preserve = ""
--reasoning-effort = "xhigh"